//! Standalone CSI config generator.
//!
//! Generates a complete UCL config file (`csi-targets.conf`) containing only
//! CSI-managed auth-groups, targets, and controllers. This file is included
//! via `.include` directive in the user's main `/etc/ctl.conf`.

use std::fmt::Write;

use crate::auth::ChapCredentials;

use super::ucl_config::{AuthGroup, ChapCredential, Controller, Target, ToUcl};

/// Generator for standalone CSI config file.
pub struct CsiConfigGenerator {
    auth_groups: Vec<(String, AuthGroup)>,
    iscsi_targets: Vec<(String, Target)>,
    nvmeof_controllers: Vec<(String, Controller)>,
}

impl CsiConfigGenerator {
    /// Create a new empty generator.
    pub fn new() -> Self {
        Self {
            auth_groups: Vec::new(),
            iscsi_targets: Vec::new(),
            nvmeof_controllers: Vec::new(),
        }
    }

    /// Add an auth group with CHAP credentials.
    pub fn add_auth_group(&mut self, name: &str, creds: &ChapCredentials) {
        let auth_group = AuthGroup {
            chap: Some(ChapCredential {
                username: creds.user.clone(),
                secret: creds.secret.clone(),
            }),
            chap_mutual: creds.mutual_user.as_ref().map(|u| ChapCredential {
                username: u.clone(),
                secret: creds.mutual_secret.clone().unwrap_or_default(),
            }),
            host_nqn: None,
        };
        self.auth_groups.push((name.to_string(), auth_group));
    }

    /// Add an iSCSI target.
    pub fn add_iscsi_target(&mut self, iqn: &str, target: Target) {
        self.iscsi_targets.push((iqn.to_string(), target));
    }

    /// Add an NVMeoF controller.
    pub fn add_nvmeof_controller(&mut self, nqn: &str, controller: Controller) {
        self.nvmeof_controllers.push((nqn.to_string(), controller));
    }

    /// Generate the complete UCL config content.
    pub fn generate(&self) -> String {
        let mut config = String::new();

        // Header
        writeln!(config, "# CSI-managed targets - DO NOT EDIT MANUALLY").unwrap();
        writeln!(config, "# Generated by ctld-agent").unwrap();
        writeln!(config, "# This file is included by /etc/ctl.conf").unwrap();
        writeln!(config).unwrap();

        // Auth groups (must come before targets that reference them)
        for (name, auth_group) in &self.auth_groups {
            writeln!(config, "auth-group \"{}\" {{", name).unwrap();
            config.push_str(&auth_group.to_ucl(1));
            writeln!(config, "}}").unwrap();
            writeln!(config).unwrap();
        }

        // iSCSI targets
        for (iqn, target) in &self.iscsi_targets {
            writeln!(config, "target \"{}\" {{", iqn).unwrap();
            config.push_str(&target.to_ucl(1));
            writeln!(config, "}}").unwrap();
            writeln!(config).unwrap();
        }

        // NVMeoF controllers
        for (nqn, controller) in &self.nvmeof_controllers {
            writeln!(config, "controller \"{}\" {{", nqn).unwrap();
            config.push_str(&controller.to_ucl(1));
            writeln!(config, "}}").unwrap();
            writeln!(config).unwrap();
        }

        config
    }

    /// Clear all entries.
    pub fn clear(&mut self) {
        self.auth_groups.clear();
        self.iscsi_targets.clear();
        self.nvmeof_controllers.clear();
    }
}

impl Default for CsiConfigGenerator {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_empty_config() {
        let generator = CsiConfigGenerator::new();
        let config = generator.generate();

        assert!(config.contains("# CSI-managed targets"));
        assert!(config.contains("# Generated by ctld-agent"));
    }

    #[test]
    fn test_generate_with_iscsi_target() {
        let mut generator = CsiConfigGenerator::new();

        let target = Target::new(
            "ag-pvc-test".to_string(),
            "pg0".to_string(),
            0,
            "/dev/zvol/tank/csi/pvc-test".to_string(),
            "pvc-test",
        );
        generator.add_iscsi_target("iqn.2024-01.org.freebsd.csi:pvc-test", target);

        let config = generator.generate();

        assert!(config.contains("target \"iqn.2024-01.org.freebsd.csi:pvc-test\""));
        assert!(config.contains("auth-group = \"ag-pvc-test\""));
        assert!(config.contains("portal-group = \"pg0\""));
        assert!(config.contains("lun 0 {"));
    }

    #[test]
    fn test_generate_with_auth_group() {
        let mut generator = CsiConfigGenerator::new();

        let creds = ChapCredentials::new("user1", "secret1");
        generator.add_auth_group("ag-pvc-test", &creds);

        let target = Target::new(
            "ag-pvc-test".to_string(),
            "pg0".to_string(),
            0,
            "/dev/zvol/tank/csi/pvc-test".to_string(),
            "pvc-test",
        );
        generator.add_iscsi_target("iqn.2024-01.org.freebsd.csi:pvc-test", target);

        let config = generator.generate();

        // Auth group should appear before target
        let auth_pos = config.find("auth-group \"ag-pvc-test\"").unwrap();
        let target_pos = config
            .find("target \"iqn.2024-01.org.freebsd.csi:pvc-test\"")
            .unwrap();
        assert!(
            auth_pos < target_pos,
            "Auth group must be defined before target"
        );

        assert!(config.contains("chap ["));
        assert!(config.contains("user = \"user1\""));
        assert!(config.contains("secret = \"secret1\""));
    }

    #[test]
    fn test_generate_with_nvmeof_controller() {
        let mut generator = CsiConfigGenerator::new();

        let controller = Controller::new(
            "no-authentication".to_string(),
            "tg0".to_string(),
            1,
            "/dev/zvol/tank/csi/pvc-nvme".to_string(),
            "pvc-nvme",
        );
        generator.add_nvmeof_controller("nqn.2024-01.org.freebsd.csi:pvc-nvme", controller);

        let config = generator.generate();

        assert!(config.contains("controller \"nqn.2024-01.org.freebsd.csi:pvc-nvme\""));
        assert!(config.contains("transport-group = \"tg0\""));
        assert!(config.contains("namespace 1 {"));
    }
}
