# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from lib.proto import ctld_agent_pb2 as ctld__agent__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in ctld_agent_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class StorageAgentStub(object):
    """The storage agent service"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateVolume = channel.unary_unary(
            "/ctld_agent.v1.StorageAgent/CreateVolume",
            request_serializer=ctld__agent__pb2.CreateVolumeRequest.SerializeToString,
            response_deserializer=ctld__agent__pb2.CreateVolumeResponse.FromString,
            _registered_method=True,
        )
        self.DeleteVolume = channel.unary_unary(
            "/ctld_agent.v1.StorageAgent/DeleteVolume",
            request_serializer=ctld__agent__pb2.DeleteVolumeRequest.SerializeToString,
            response_deserializer=ctld__agent__pb2.DeleteVolumeResponse.FromString,
            _registered_method=True,
        )
        self.ExpandVolume = channel.unary_unary(
            "/ctld_agent.v1.StorageAgent/ExpandVolume",
            request_serializer=ctld__agent__pb2.ExpandVolumeRequest.SerializeToString,
            response_deserializer=ctld__agent__pb2.ExpandVolumeResponse.FromString,
            _registered_method=True,
        )
        self.ListVolumes = channel.unary_unary(
            "/ctld_agent.v1.StorageAgent/ListVolumes",
            request_serializer=ctld__agent__pb2.ListVolumesRequest.SerializeToString,
            response_deserializer=ctld__agent__pb2.ListVolumesResponse.FromString,
            _registered_method=True,
        )
        self.GetVolume = channel.unary_unary(
            "/ctld_agent.v1.StorageAgent/GetVolume",
            request_serializer=ctld__agent__pb2.GetVolumeRequest.SerializeToString,
            response_deserializer=ctld__agent__pb2.GetVolumeResponse.FromString,
            _registered_method=True,
        )
        self.CreateSnapshot = channel.unary_unary(
            "/ctld_agent.v1.StorageAgent/CreateSnapshot",
            request_serializer=ctld__agent__pb2.CreateSnapshotRequest.SerializeToString,
            response_deserializer=ctld__agent__pb2.CreateSnapshotResponse.FromString,
            _registered_method=True,
        )
        self.DeleteSnapshot = channel.unary_unary(
            "/ctld_agent.v1.StorageAgent/DeleteSnapshot",
            request_serializer=ctld__agent__pb2.DeleteSnapshotRequest.SerializeToString,
            response_deserializer=ctld__agent__pb2.DeleteSnapshotResponse.FromString,
            _registered_method=True,
        )
        self.ListSnapshots = channel.unary_unary(
            "/ctld_agent.v1.StorageAgent/ListSnapshots",
            request_serializer=ctld__agent__pb2.ListSnapshotsRequest.SerializeToString,
            response_deserializer=ctld__agent__pb2.ListSnapshotsResponse.FromString,
            _registered_method=True,
        )
        self.GetSnapshot = channel.unary_unary(
            "/ctld_agent.v1.StorageAgent/GetSnapshot",
            request_serializer=ctld__agent__pb2.GetSnapshotRequest.SerializeToString,
            response_deserializer=ctld__agent__pb2.GetSnapshotResponse.FromString,
            _registered_method=True,
        )
        self.GetCapacity = channel.unary_unary(
            "/ctld_agent.v1.StorageAgent/GetCapacity",
            request_serializer=ctld__agent__pb2.GetCapacityRequest.SerializeToString,
            response_deserializer=ctld__agent__pb2.GetCapacityResponse.FromString,
            _registered_method=True,
        )


class StorageAgentServicer(object):
    """The storage agent service"""

    def CreateVolume(self, request, context):
        """Volume operations"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteVolume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ExpandVolume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListVolumes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetVolume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreateSnapshot(self, request, context):
        """Snapshot operations"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListSnapshots(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetCapacity(self, request, context):
        """Capacity information"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_StorageAgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "CreateVolume": grpc.unary_unary_rpc_method_handler(
            servicer.CreateVolume,
            request_deserializer=ctld__agent__pb2.CreateVolumeRequest.FromString,
            response_serializer=ctld__agent__pb2.CreateVolumeResponse.SerializeToString,
        ),
        "DeleteVolume": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteVolume,
            request_deserializer=ctld__agent__pb2.DeleteVolumeRequest.FromString,
            response_serializer=ctld__agent__pb2.DeleteVolumeResponse.SerializeToString,
        ),
        "ExpandVolume": grpc.unary_unary_rpc_method_handler(
            servicer.ExpandVolume,
            request_deserializer=ctld__agent__pb2.ExpandVolumeRequest.FromString,
            response_serializer=ctld__agent__pb2.ExpandVolumeResponse.SerializeToString,
        ),
        "ListVolumes": grpc.unary_unary_rpc_method_handler(
            servicer.ListVolumes,
            request_deserializer=ctld__agent__pb2.ListVolumesRequest.FromString,
            response_serializer=ctld__agent__pb2.ListVolumesResponse.SerializeToString,
        ),
        "GetVolume": grpc.unary_unary_rpc_method_handler(
            servicer.GetVolume,
            request_deserializer=ctld__agent__pb2.GetVolumeRequest.FromString,
            response_serializer=ctld__agent__pb2.GetVolumeResponse.SerializeToString,
        ),
        "CreateSnapshot": grpc.unary_unary_rpc_method_handler(
            servicer.CreateSnapshot,
            request_deserializer=ctld__agent__pb2.CreateSnapshotRequest.FromString,
            response_serializer=ctld__agent__pb2.CreateSnapshotResponse.SerializeToString,
        ),
        "DeleteSnapshot": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteSnapshot,
            request_deserializer=ctld__agent__pb2.DeleteSnapshotRequest.FromString,
            response_serializer=ctld__agent__pb2.DeleteSnapshotResponse.SerializeToString,
        ),
        "ListSnapshots": grpc.unary_unary_rpc_method_handler(
            servicer.ListSnapshots,
            request_deserializer=ctld__agent__pb2.ListSnapshotsRequest.FromString,
            response_serializer=ctld__agent__pb2.ListSnapshotsResponse.SerializeToString,
        ),
        "GetSnapshot": grpc.unary_unary_rpc_method_handler(
            servicer.GetSnapshot,
            request_deserializer=ctld__agent__pb2.GetSnapshotRequest.FromString,
            response_serializer=ctld__agent__pb2.GetSnapshotResponse.SerializeToString,
        ),
        "GetCapacity": grpc.unary_unary_rpc_method_handler(
            servicer.GetCapacity,
            request_deserializer=ctld__agent__pb2.GetCapacityRequest.FromString,
            response_serializer=ctld__agent__pb2.GetCapacityResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "ctld_agent.v1.StorageAgent", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "ctld_agent.v1.StorageAgent", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class StorageAgent(object):
    """The storage agent service"""

    @staticmethod
    def CreateVolume(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ctld_agent.v1.StorageAgent/CreateVolume",
            ctld__agent__pb2.CreateVolumeRequest.SerializeToString,
            ctld__agent__pb2.CreateVolumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteVolume(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ctld_agent.v1.StorageAgent/DeleteVolume",
            ctld__agent__pb2.DeleteVolumeRequest.SerializeToString,
            ctld__agent__pb2.DeleteVolumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ExpandVolume(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ctld_agent.v1.StorageAgent/ExpandVolume",
            ctld__agent__pb2.ExpandVolumeRequest.SerializeToString,
            ctld__agent__pb2.ExpandVolumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListVolumes(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ctld_agent.v1.StorageAgent/ListVolumes",
            ctld__agent__pb2.ListVolumesRequest.SerializeToString,
            ctld__agent__pb2.ListVolumesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetVolume(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ctld_agent.v1.StorageAgent/GetVolume",
            ctld__agent__pb2.GetVolumeRequest.SerializeToString,
            ctld__agent__pb2.GetVolumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CreateSnapshot(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ctld_agent.v1.StorageAgent/CreateSnapshot",
            ctld__agent__pb2.CreateSnapshotRequest.SerializeToString,
            ctld__agent__pb2.CreateSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteSnapshot(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ctld_agent.v1.StorageAgent/DeleteSnapshot",
            ctld__agent__pb2.DeleteSnapshotRequest.SerializeToString,
            ctld__agent__pb2.DeleteSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListSnapshots(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ctld_agent.v1.StorageAgent/ListSnapshots",
            ctld__agent__pb2.ListSnapshotsRequest.SerializeToString,
            ctld__agent__pb2.ListSnapshotsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetSnapshot(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ctld_agent.v1.StorageAgent/GetSnapshot",
            ctld__agent__pb2.GetSnapshotRequest.SerializeToString,
            ctld__agent__pb2.GetSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetCapacity(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ctld_agent.v1.StorageAgent/GetCapacity",
            ctld__agent__pb2.GetCapacityRequest.SerializeToString,
            ctld__agent__pb2.GetCapacityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
