apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: freebsd-e2e-iscsi-linked
  labels:
    app.kubernetes.io/component: e2e-testing
    app.kubernetes.io/part-of: freebsd-csi
provisioner: csi.freebsd.org
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  # Export volume via iSCSI
  exportType: iscsi
  # Storage target endpoints (required for Linux initiators)
  endpoints: "10.0.0.10:3260,10.0.0.11:3260"
  # Filesystem type
  fsType: ext4
  # Use LINKED clone mode (fast, with dependency)
  cloneMode: linked
