apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: freebsd-e2e-iscsi-chap
  labels:
    app.kubernetes.io/component: e2e-testing
    app.kubernetes.io/part-of: freebsd-csi
provisioner: csi.freebsd.org
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  # Export volume via iSCSI
  exportType: iscsi
  # Storage target endpoints (required for Linux initiators)
  endpoints: "10.0.0.10:3260"
  # Filesystem type
  fsType: ext4
  # CHAP secret references for provisioner (controller)
  csi.storage.k8s.io/provisioner-secret-name: ${pvc.name}-chap
  csi.storage.k8s.io/provisioner-secret-namespace: ${pvc.namespace}
  # CHAP secret references for node staging
  csi.storage.k8s.io/node-stage-secret-name: ${pvc.name}-chap
  csi.storage.k8s.io/node-stage-secret-namespace: ${pvc.namespace}
