apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: freebsd-e2e-iscsi-copy
  labels:
    app.kubernetes.io/component: e2e-testing
    app.kubernetes.io/part-of: freebsd-csi
provisioner: csi.freebsd.org
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  # Export volume via iSCSI
  exportType: iscsi
  # Use COPY clone mode (slow, fully independent)
  cloneMode: copy
